# Generated by Django 5.1.5 on 2025-02-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_job_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
