# Generated by Django 5.1.5 on 2025-02-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_job_company_delete_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='qualifications',
            new_name='benefits',
        ),
        migrations.AddField(
            model_name='job',
            name='requirements',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='job',
            name='more_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='posted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
