# Generated by Django 5.1.5 on 2025-05-13 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_job_industry_alter_job_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='company_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='company_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('job_seeker', 'Job Seeker'), ('recruiter', 'Recruiter')], default='job_seeker', max_length=20),
        ),
    ]
